Update extractor.py
This file is giving error 
AttributeError: module 'tensorflow' has no attribute 'Session' - in line 18
So, we will have to use tf.compat.v1.Session() instead of tf.Session()